### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by Ossii** [SadBatman/cryptonote-sumokoin-pool#18]
I see I used completely wrong files (repo) as I copied and pasted instructions when doing the final setup.
Which made me use old repo (billaue2's). I did clone now and copied over certs and config.json.
However this throws these errors:

TypeError: Cannot read property 'indexOf' of undefined
    at handleMinerMethod (/home/sumopool/pool/lib/pool.js:594:62)
    at handleMessage (/home/sumopool/pool/lib/pool.js:740:13)
    at Socket.<anonymous> (/home/sumopool/pool/lib/pool.js:794:25)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)

2017-12-19 16:07:54 [master] Pool fork 2 died, spawning replacement worker...

Any idea where I might have gone wrong here?

**Comment by Ossii** [comment]
Clean config file solved it
