### ISSUE TITLE
Charts collector died

### ISSUE THREAD

**Issue by SadBatman** [SadBatman/cryptonote-sumokoin-pool#19]
It died with this error two times today:

2017-12-19 17:37:45
TypeError: Cannot read property 'error' of undefined
    at /home/ninen/cryptonote-sumokoin-pool/lib/charts.js:188:26
    at IncomingMessage.<anonymous> (/home/ninen/cryptonote-sumokoin-pool/lib/apiInterfaces.js:31:17)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)

**Comment by tlacicer** [comment]
same here

**Comment by SadBatman** [comment]
This happens when the cryptonator API is unreachable:

```
186 function getCoinPrice(callback) {                                                
187     apiInterfaces.jsonHttpRequest('api.cryptonator.com', 443, '', function(error, response) {
188         callback(response.error ? response.error : error, response.success ? +response.ticker.price : null);                                                                                                    
189     }, '/api/ticker/' + config.symbol.toLowerCase() + '-usd');                   
190 }    
```

**Comment by SadBatman** [comment]
This should be fixed now.
