### ISSUE TITLE
npm update failed

### ISSUE THREAD

**Issue by Halfbax** [SadBatman/cryptonote-sumokoin-pool#24]
ubuntu-server 17.10
npm 3.5.2
nodejs 6.11.4

How do I fix it?
```
npm update

> cryptonote-util@0.0.1 install /home/pool/node_modules/cryptonote-util
> node-gyp rebuild

make: Entering directory '/home/pool/node_modules/cryptonote-util/build'
  CXX(target) Release/obj.target/cryptonote/src/main.o
  CXX(target) Release/obj.target/cryptonote/src/cryptonote_core/cryptonote_format_utils.o
../src/cryptonote_core/cryptonote_format_utils.cpp: In function ‘bool cryptonote::check_proof_of_work(const cryptonote::block&, cryptonote::difficulty                                                                                                                                                                        _type, crypto::hash&)’:
../src/cryptonote_core/cryptonote_format_utils.cpp:938:3: warning: no return statement in function returning non-void [-Wreturn-type]
   }
   ^
  CC(target) Release/obj.target/cryptonote/src/crypto/tree-hash.o
  CXX(target) Release/obj.target/cryptonote/src/crypto/crypto.o
../src/crypto/crypto.cpp: In function ‘std::size_t crypto::rs_comm_size(std::size_t)’:
../src/crypto/crypto.cpp:224:58: error: value-initialization of incomplete type ‘crypto::rs_comm::<unnamed struct> []’
     return sizeof(rs_comm) + pubs_count * sizeof(rs_comm().ab[0]);
                                                          ^
cryptonote.target.mk:114: recipe for target 'Release/obj.target/cryptonote/src/crypto/crypto.o' failed
make: *** [Release/obj.target/cryptonote/src/crypto/crypto.o] Error 1
make: Leaving directory '/home/pool/node_modules/cryptonote-util/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 4.13.0-21-generic
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/pool/node_modules/cryptonote-util
gyp ERR! node -v v6.11.4
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
cryptonote-universal-pool@0.0.1 /home/pool
└── multi-hashing@0.0.9  (git://github.com/clintar/node-multi-hashing.git#6df2cd104c0dcc5dceea216c1fcadbbbd0986552)

npm ERR! Linux 4.13.0-21-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "update"
npm ERR! node v6.11.4
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! cryptonote-util@0.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cryptonote-util@0.0.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cryptonote-util package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cryptonote-util
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cryptonote-util
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pool/npm-debug.log
```

**Comment by KevinCHill** [comment]
+1 - I'm getting the same error:
Ubuntu 17.10
'cryptonote-universal-pool': '0.0.1',
  npm: '5.5.1',
  ares: '1.13.0',
  cldr: '32.0',
  http_parser: '2.7.0',
  icu: '60.1',
  modules: '59',
  nghttp2: '1.25.0',
  node: '9.3.0',
  openssl: '1.0.2n',
  tz: '2017c',
  unicode: '10.0',
  uv: '1.18.0',
  v8: '6.2.414.46-node.15',
  zlib: '1.2.11'

make: Leaving directory '/var/pool/node_modules/cryptonote-util/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.13.0-16-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/pool/node_modules/cryptonote-util
gyp ERR! node -v v9.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cryptonote-util@0.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cryptonote-util@0.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by SadBatman** [comment]
Can you try with GCC 5 ?

**Comment by Halfbax** [comment]
What do you mean? Can you give me an example?

**Comment by KevinCHill** [comment]
I'm using gcc version 7.2.0 (Ubuntu 7.2.0-8ubuntu3)  - are you suggesting I downgrade?

**Comment by SadBatman** [comment]
Yeah this is a known issue with newer versions of GCC and the the nodejs cryptonote package.

**Comment by cryptogrot** [comment]
On Ubuntu Trusty 14.04 with GCC 5.4, I'm able to compile.
How many memory do you have ? I had to increase the memory of my VPS to 2Gb to make it compile.

**Comment by SadBatman** [comment]
Hey guys I'm closing this out as I think the solution is to use GCC 5 (which isn't great but it's also not the end of the world).

**Comment by SadBatman** [comment]
Actually - can you edit package.json and change the github of cryptonote-util and update it to github.com/druide/node-cryptonote-util.git ? Maybe this allows you to compile it.

**Comment by Ossii** [comment]
It allows it to compile with that fix. However, I'm seeing a strange issue on the server where I had to use this fix (debian stretch).

```
[pool] (Thread 26) New block to mine at height 92077 w/ difficulty of 5494485236
2018-01-17 09:16:38 [pool] (Thread 22) New block to mine at height 92077 w/ difficulty of 5494485236
2018-01-17 09:16:39 [pool] (Thread 29) New block to mine at height 92077 w/ difficulty of 5494485236
2018-01-17 09:16:39 [pool] (Thread 19) Error polling getblockcount {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":19734}
2018-01-17 09:16:39 [pool] (Thread 17) Error polling getblockcount {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":19734}
```

Can this be related to above fix? Not seeing this on my ubuntu16 pool VPS where I'm not using this fix (compiled fine there..)

**Comment by Ossii** [comment]
Confirmed working for me with using github.com/druide/node-cryptonote-util.git

**Comment by MyS5Droid** [comment]
Not working for me with github.com/druide/node-cryptonote-util.git
Not able to install gcc-5 and g++-5 in Stretch
