### ISSUE TITLE
node init.js error with mailgun

### ISSUE THREAD

**Issue by KevinCHill** [SadBatman/cryptonote-sumokoin-pool#26]
/var/pool/node_modules/mailgun.js/lib/client.js:18
class Client {
^^^^^

SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/pool/node_modules/mailgun.js/index.js:5:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by mrtiritas** [comment]
You have to upgrade your node version.

You may use latest version. It's tested.

**Comment by KevinCHill** [comment]
thank you so much for your help., so i'm now at node 9.3.0 that solved that error, but now i have a new one:

2017-12-30 14:27:08 [master] Pool spawned on 2 thread(s)
2017-12-30 14:27:08 [charts] Started
2017-12-30 14:27:08 [charts] Started
2017-12-30 14:27:08 [chartsDataCollector] Started
2017-12-30 14:27:08 [unlocker] Started
2017-12-30 14:27:08 [unlocker] No blocks candidates in redis
module.js:670
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: Module did not self-register.
    at Object.Module._extensions..node (module.js:670:18)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/pool/node_modules/bignum/index.js:4:11)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
(node:22816) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.

**Comment by SadBatman** [comment]
Delete node_modules and run npm upgrade again
