### ISSUE TITLE
help with mailgun config 

### ISSUE THREAD

**Issue by AhmedSh3ban** [SadBatman/cryptonote-sumokoin-pool#29]
node_modules/mailgun.js/lib/client.js:18
class Client {
^^^^^

SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/coinwire/sumopool/node_modules/mailgun.js/index.js:5:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by SadBatman** [comment]
What node version are you using ?

**Comment by AhmedSh3ban** [comment]
Ubuntu 14.04 x64
node 0.10.25

**Comment by AhmedSh3ban** [comment]
root:~$ node -v
v0.10.25
root:~$ npm -v
1.3.10
root:~$ redis-server -v
Redis server v=2.8.4

**Comment by AhmedSh3ban** [comment]
i followed this steps and everything works now 👍 
@root: curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
@root: sudo apt-get install -y nodejs

@root: node-v 
v4.8.7

@root: rm-rf node_modules
@root: npm update 

-------------------------------------------- thanks SadBatman <3
