### ISSUE TITLE
I have a huge problem starting node

### ISSUE THREAD

**Issue by Ingerulro** [SadBatman/cryptonote-sumokoin-pool#33]
`Error: bind EADDRINUSE null:5555
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at cb (net.js:1302:16)
    at rr (cluster.js:594:14)
    at Worker.<anonymous> (cluster.js:564:9)
    at process.<anonymous> (cluster.js:714:8)
    at emitTwo (events.js:92:20)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:689:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)

2018-01-06 10:00:12 [pool] (Thread 1) Started server listening on port 3333
2018-01-06 10:00:12 [pool] (Thread 1) SSL Started server listening on port 3334
2018-01-06 10:00:12 [pool] (Thread 1) Started server listening on port 4444
2018-01-06 10:00:12 [pool] (Thread 1) SSL Started server listening on port 4445
2018-01-06 10:00:12 [pool] (Thread 1) Started server listening on port 5555

TypeError: Cannot read property 'apply' of undefined
    at process.<anonymous> (cluster.js:714:7)
    at emitTwo (events.js:92:20)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:689:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)

2018-01-06 10:00:12 [master] Pool fork 1 died, spawning replacement worker...`

**Comment by Ossii** [comment]
I dunno about the rest, but the first line gives some answers.
Port 5555 is already in use, try to use 5556 just for test and see if the rest of the errors disappears.
If so then use netstat -l to figure out whats using port 5555

**Comment by yrjo** [comment]
check the config and ports for workers, you do have probably 5555 two times there (as there is also typo in example config file - that can be fixed here i guess)
