### ISSUE TITLE
Pool will not initiate

### ISSUE THREAD

**Issue by nravanelli** [SadBatman/cryptonote-sumokoin-pool#62]
I keep trying to figure this out, but have no idea why I get this error.

here is what happens repetitively after sudo node init.js

```
2018-04-05 13:54:00 [api] Stat collection finished: 63 ms redis, 60 ms daemon
2018-04-05 13:54:00 [master] API died, spawning replacement...
2018-04-05 13:54:01 [pool] (Thread 4) New block to mine at height 39291 w/ difficulty of 505460851

TypeError: path must be a string
    at TypeError (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at /root/pool/lib/pool.js:809:21
    at /root/pool/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (/root/pool/node_modules/async/lib/async.js:233:13)
    at Object.async.forEach.async.each (/root/pool/node_modules/async/lib/async.js:209:22)
    at startPoolServerTcp (/root/pool/lib/pool.js:714:11)
    at jobRefreshCompleteCallback (/root/pool/lib/pool.js:263:9)
    at /root/pool/lib/pool.js:232:17

2018-04-05 13:54:01 [master] Pool fork 4 died, spawning replacement worker...
2018-04-05 13:54:01 [pool] (Thread 1) New block to mine at height 39291 w/ difficulty of 505460851
2018-04-05 13:54:01 [pool] (Thread 3) Blockchain height changed to 0, updating template.

TypeError: path must be a string
    at TypeError (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at /root/pool/lib/pool.js:809:21
    at /root/pool/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (/root/pool/node_modules/async/lib/async.js:233:13)
    at Object.async.forEach.async.each (/root/pool/node_modules/async/lib/async.js:209:22)
    at startPoolServerTcp (/root/pool/lib/pool.js:714:11)
    at jobRefreshCompleteCallback (/root/pool/lib/pool.js:263:9)
    at /root/pool/lib/pool.js:232:17


TypeError: path must be a string
    at TypeError (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at /root/pool/lib/pool.js:809:21
    at /root/pool/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (/root/pool/node_modules/async/lib/async.js:233:13)
    at Object.async.forEach.async.each (/root/pool/node_modules/async/lib/async.js:209:22)
    at startPoolServerTcp (/root/pool/lib/pool.js:714:11)
    at jobRefreshCompleteCallback (/root/pool/lib/pool.js:263:9)
    at /root/pool/lib/pool.js:203:22

2018-04-05 13:54:01 [pool] (Thread 3) New block to mine at height 39291 w/ difficulty of 505460851
2018-04-05 13:54:01 [master] Pool fork 1 died, spawning replacement worker...

TypeError: path must be a string
    at TypeError (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at /root/pool/lib/pool.js:809:21
    at /root/pool/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (/root/pool/node_modules/async/lib/async.js:233:13)
    at Object.async.forEach.async.each (/root/pool/node_modules/async/lib/async.js:209:22)
    at startPoolServerTcp (/root/pool/lib/pool.js:714:11)
    at jobRefreshCompleteCallback (/root/pool/lib/pool.js:263:9)
    at /root/pool/lib/pool.js:232:17


TypeError: path must be a string
    at TypeError (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at /root/pool/lib/pool.js:809:21
    at /root/pool/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (/root/pool/node_modules/async/lib/async.js:233:13)
    at Object.async.forEach.async.each (/root/pool/node_modules/async/lib/async.js:209:22)
    at startPoolServerTcp (/root/pool/lib/pool.js:714:11)
    at jobRefreshCompleteCallback (/root/pool/lib/pool.js:263:9)
    at /root/pool/lib/pool.js:203:22

2018-04-05 13:54:02 [master] Pool fork 3 died, spawning replacement worker...
2018-04-05 13:54:03 [pool] (Thread 5) New block to mine at height 39291 w/ difficulty of 505460851

TypeError: path must be a string
    at TypeError (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at /root/pool/lib/pool.js:809:21
    at /root/pool/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (/root/pool/node_modules/async/lib/async.js:233:13)
    at Object.async.forEach.async.each (/root/pool/node_modules/async/lib/async.js:209:22)
    at startPoolServerTcp (/root/pool/lib/pool.js:714:11)
    at jobRefreshCompleteCallback (/root/pool/lib/pool.js:263:9)
    at /root/pool/lib/pool.js:232:17
```
I can see that it is communicating with the daemon, and is communicating with redis, but what is the TypeError: path must be a string ?

Thanks.

**Comment by dp-unique** [comment]
Getting Same errors.
