### ISSUE TITLE
key.pem error

### ISSUE THREAD

**Issue by nutsplus** [SadBatman/cryptonote-sumokoin-pool#64]
Error: ENOENT: no such file or directory, open 'key.pem'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at /home/nuts/pool/lib/pool.js:809:21
    at /home/nuts/pool/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (/home/nuts/pool/node_modules/async/lib/async.js:233:13)
    at Object.async.forEach.async.each (/home/nuts/pool/node_modules/async/lib/async.js:209:22)
    at startPoolServerTcp (/home/nuts/pool/lib/pool.js:714:11)
    at jobRefreshCompleteCallback (/home/nuts/pool/lib/pool.js:263:9)
    at /home/nuts/pool/lib/pool.js:232:17

**Comment by SadBatman** [comment]
Disable ports with SSL or alternatively create a cert and call the key key.pem

**Comment by nutsplus** [comment]
How I can do that?? Thx
