### ISSUE TITLE
Many errors

### ISSUE THREAD

**Issue by vrl112** [SadBatman/cryptonote-sumokoin-pool#67]
Hello , I'm using the last release , in admin everything is with status OK , but in master_error.log i have over 300 errors like this : 

> 2018-05-02 09:20:37 chartsDataCollector died, spawning replacement...
> 2018-05-02 09:37:04 Pool fork 2 died, spawning replacement worker...
> 2018-05-02 09:38:24 Pool fork 1 died, spawning replacement worker...

And in pool_crash.log : 
2018-05-02 09:38:24
TypeError: Cannot read property 'heartbeat' of undefined
    at handleMinerMethod (/root/poolv3/lib/pool.js:697:18)
    at handleMessage (/root/poolv3/lib/pool.js:740:13)
    at Socket.<anonymous> (/root/poolv3/lib/pool.js:794:25)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)

The last block found was on 4/18/2018 after that he found on 4/27/2018 ( orphaned ) and that's it , till now he didn't found new block . Today is 5/2/2018 , is it normal ? thank you

**Comment by Ossii** [comment]
Did you upgrade for the fork that sumokoin did?
Both pool and daemon/wallet?

**Comment by vrl112** [comment]
yes , pool / daemon and the wallet are latest versions

this is my api call with status ok : http://54.37.75.69:8118/health

**Comment by Ossii** [comment]
Ah yeah I see you found a block 5 days ago, and with the hashrate you have in the pool you should find a block aprox every 5 days. so then all that is ok, just need more hashrate to find the blocks quicker.

For the error, I cant say if its a problem or not, but as long as health says ok, then things should be ok...

**Comment by vrl112** [comment]
that block was orphaned, i know that with my hashrate i will find every x days , depends on diff, if is like this , the pool is working fine , but  what is with my errors :( because i don't understand , on pool is a miner with the old algorithm( i saw bad hash in admin ) , is from that ?
